name: Run Tests

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    services:
      fauna:
        image: fauna/faunadb
        ports:
          - 8443:8443
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: corretto
      - name: Install fauna-shell
        run:
          npm install -g fauna-shell
      - name: Setup Test Database
        run: ./test/setup.sh

      - name: Test sample app
        run: |
          ./gradlew build
          FAUNA_ENDPOINT=http://localhost:8443 FAUNA_SECRET=`cat .fauna_key` ./gradlew bootRun > bootrun.log 2>&1  &
          ./test/validate.sh
          cat bootrun.log